export const PLAYERS = {
  XIAN: [
    { name: 'Bin', imageName: 'bin' },
    { name: 'Shuming', imageName: 'shuming' },
    { name: 'Yingjian', imageName: 'yingjian' },
    { name: 'Yixing', imageName: 'yixing' },
  ],
  MELB: [
    { name: 'Albert', imageName: 'albert' },
    { name: 'Alex', imageName: 'alex' },
    { name: 'Andy', imageName: 'andy' },
    { name: 'Azra', imageName: 'azra' },
    { name: 'Chris', imageName: 'chris' },
    { name: 'Du', imageName: 'du' },
    { name: 'Duyen', imageName: 'duyen' },
    { name: 'Jay', imageName: 'jay' },
    { name: 'Jim', imageName: 'jim' },
    { name: 'Liujing', imageName: 'liujing' },
    { name: 'Marion', imageName: 'marion' },
    { name: 'Michael B', imageName: 'michael_b' },
    { name: 'Michael W', imageName: 'michael_w' },
    { name: 'Stacey', imageName: 'stacey' },
    { name: 'Ray', imageName: 'ray' },
    { name: 'Yujin', imageName: 'yujin' },
  ],
};
