import { RacerHistoryRecord, RacerHistoryRecordsByDay } from '../types';

export const mockFlatHistory: RacerHistoryRecord[] = [
  {
    playerId: 'zijian',
    position: { sectionIndex: 5, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'zijian',
    position: { sectionIndex: 5, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'vishnu',
    position: { sectionIndex: 6, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'vishnu',
    position: { sectionIndex: 7, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'vishnu',
    position: { sectionIndex: 7, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 11, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 12, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 13, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 14, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'harry',
    position: { sectionIndex: 4, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'harry',
    position: { sectionIndex: 4, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 9, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 10, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 11, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 12, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'stacey_l',
    position: { sectionIndex: 6, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'stacey_l',
    position: { sectionIndex: 6, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'marion',
    position: { sectionIndex: 1, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'marion',
    position: { sectionIndex: 2, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'marion',
    position: { sectionIndex: 3, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'james',
    position: { sectionIndex: 5, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'james',
    position: { sectionIndex: 6, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'james',
    position: { sectionIndex: 6, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'chris',
    position: { sectionIndex: 9, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'chris',
    position: { sectionIndex: 10, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'chris',
    position: { sectionIndex: 11, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'stacey',
    position: { sectionIndex: 2, laneIndex: 2, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'stacey',
    position: { sectionIndex: 3, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'rishita',
    position: { sectionIndex: 7, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'rishita',
    position: { sectionIndex: 8, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'pratik',
    position: { sectionIndex: 8, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'pratik',
    position: { sectionIndex: 9, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 0, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 1, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 11, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 12, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'albert_s',
    position: { sectionIndex: 7, laneIndex: 1, squareIndex: 1 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'albert_s',
    position: { sectionIndex: 8, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 12, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 13, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 14, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'alex',
    position: { sectionIndex: 14, laneIndex: 1, squareIndex: 1 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 12, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 13, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 14, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'andy',
    position: { sectionIndex: 14, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 1, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 2, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 3, laneIndex: 2, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'carol',
    position: { sectionIndex: 4, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'ma_hong',
    position: { sectionIndex: 5, laneIndex: 2, squareIndex: 0 },
    movesRemaining: 3,
    blocked: false,
  },
  {
    playerId: 'ma_hong',
    position: { sectionIndex: 5, laneIndex: 2, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'pratik',
    position: { sectionIndex: 9, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'pratik',
    position: { sectionIndex: 10, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'pratik',
    position: { sectionIndex: 11, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'rishita',
    position: { sectionIndex: 8, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'rishita',
    position: { sectionIndex: 9, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'rishita',
    position: { sectionIndex: 10, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'ying',
    position: { sectionIndex: 5, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'ying',
    position: { sectionIndex: 5, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'zijian',
    position: { sectionIndex: 5, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 2,
    blocked: false,
  },
  {
    playerId: 'zijian',
    position: { sectionIndex: 5, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
  {
    playerId: 'chris',
    position: { sectionIndex: 11, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'chris',
    position: { sectionIndex: 12, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'harry',
    position: { sectionIndex: 4, laneIndex: 3, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'harry',
    position: { sectionIndex: 5, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'james',
    position: { sectionIndex: 6, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'james',
    position: { sectionIndex: 7, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 14, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'shuming',
    position: { sectionIndex: 15, laneIndex: 0, squareIndex: 0 },
    movesRemaining: 0,
    blocked: false,
  },
  {
    playerId: 'stacey_l',
    position: { sectionIndex: 6, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 1,
    blocked: false,
  },
  {
    playerId: 'stacey_l',
    position: { sectionIndex: 6, laneIndex: 1, squareIndex: 0 },
    movesRemaining: 0,
    blocked: true,
  },
];

export const mockHistory: RacerHistoryRecordsByDay[] = [
  {
    date: 'day 1',
    history: [
      {
        playerId: 'andy',
        position: {
          sectionIndex: 4,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 5,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 6,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 7,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 4,
          laneIndex: 1,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 5,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 6,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 7,
          laneIndex: 1,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 1,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 2,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 3,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 4,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
    ],
  },
  {
    date: 'day 2',
    history: [
      {
        playerId: 'andy',
        position: {
          sectionIndex: 7,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 4,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 8,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 9,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 10,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 11,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 7,
          laneIndex: 1,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 7,
          laneIndex: 1,
          squareIndex: 1,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 4,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 5,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
    ],
  },
  {
    date: 'day 3',
    history: [
      {
        playerId: 'andy',
        position: {
          sectionIndex: 0,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 4,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 1,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 2,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 3,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'andy',
        position: {
          sectionIndex: 4,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 0,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 4,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 1,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 3,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 2,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 2,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 3,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'alex',
        position: {
          sectionIndex: 4,
          laneIndex: 1,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 0,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 1,
        blocked: false,
      },
      {
        playerId: 'albert_s',
        position: {
          sectionIndex: 1,
          laneIndex: 0,
          squareIndex: 0,
        },
        movesRemaining: 0,
        blocked: false,
      },
    ],
  },
];
