#!/bin/bash -eu

cd $(dirname $0)/..

REACT_APP_COUNTER_API_BASE_URL="https://counterapi.tangarineturkey.com/api/counter/group/27bb17f6-070d-484b-8799-d5f27e4eb073"
REACT_APP_PRODUCTION="false"
docker build \
--build-arg counter_api_base_url=${REACT_APP_COUNTER_API_BASE_URL} \
--build-arg is_production=${REACT_APP_PRODUCTION} \
-t supersquad/cowboy-ninja-bear-staging:latest .
