#!/bin/bash -eu

cd $(dirname $0)/..

ecsTagname="766741520701.dkr.ecr.ap-southeast-2.amazonaws.com/supersquad/cnb-repo-prod:latest"

docker tag supersquad/cowboy-ninja-bear-prod:latest ${ecsTagname}
docker push ${ecsTagname}