import { PlayerList } from './types';

const tournamentTag = 'tournament';
const retired = 'retired';

export const ALL_PLAYERS: PlayerList = [
  { name: 'Albert', id: 'albert', tags: [tournamentTag] },
  { name: 'Alex', id: 'alex', tags: [tournamentTag] },
  { name: 'Andy', id: 'andy', tags: [tournamentTag] },
  { name: 'Azra', id: 'azra', tags: [tournamentTag] },
  { name: 'Bec', id: 'bec', tags: [tournamentTag] },
  { name: 'Bin', id: 'bin', tags: [tournamentTag] },
  { name: 'Bjorn', id: 'bjorn', tags: [retired] },
  { name: 'Chris', id: 'chris', tags: [tournamentTag] },
  { name: 'Du', id: 'du', tags: [tournamentTag] },
  { name: 'Dunny', id: 'dunny', tags: [tournamentTag] },
  { name: 'Duyen', id: 'duyen', tags: [tournamentTag] },
  { name: 'Jatin', id: 'jatin', tags: [retired] },
  { name: 'Jay', id: 'jay', tags: [tournamentTag] },
  { name: 'Jim', id: 'jim', tags: [tournamentTag] },
  { name: 'Liujing', id: 'liujing', tags: [tournamentTag] },
  { name: 'Marion', id: 'marion', tags: [tournamentTag] },
  { name: 'Michael B', id: 'michael_b', tags: [tournamentTag] },
  { name: 'Stacey', id: 'stacey', tags: [tournamentTag] },
  { name: 'Ray', id: 'ray', tags: [retired] },
  { name: 'Ricky', id: 'ricky', tags: [tournamentTag] },
  { name: 'Shuming', id: 'shuming', tags: [tournamentTag] },
  { name: 'Sime', id: 'sime', tags: [tournamentTag] },
  { name: 'Yingjian', id: 'yingjian', tags: [tournamentTag] },
  { name: 'Yixing', id: 'yixing', tags: [tournamentTag] },
  { name: 'Yujin', id: 'yujin', tags: [tournamentTag] },
];

export const ALL_TEAMS = [
  { id: 'xian', name: 'Xian' },
  { id: 'melb', name: 'Melbourne' },
  { id: 'us', name: 'Us' },
  { id: 'them', name: 'Them' },
  { id: 'team_a', name: 'Team A' },
  { id: 'team_2', name: 'Team 2' },
  { id: 'dropping_bombs', name: 'Dropping Bombs' },
  { id: 'silvinstones', name: 'Silvinstones' },
  { id: 'cowboy_needs_a_beer', name: 'Cowboy Needs a Beer' },
  { id: 'go_duck', name: 'Go Duck' },
  { id: 'a_team', name: 'The A Team' },
  { id: 'bake_my_day', name: 'Bake My Day' },
];

export const PLAYER_IDS_BY_TEAM: { [teamId: string]: string[] } = {
  xian: ['bin', 'shuming', 'yingjian', 'yixing'],
  melb: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bjorn',
    'chris',
    'du',
    'duyen',
    'jatin',
    'jay',
    'jim',
    'liujing',
    'marion',
    'michael_b',
    'stacey',
    'ray',
    'ricky',
    'yujin',
  ],
  us: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bin',
    'bjorn',
    'chris',
    'du',
    'duyen',
    'jatin',
    'jay',
  ],
  them: [
    'yixing',
    'yujin',
    'yingjian',
    'shuming',
    'ray',
    'stacey',
    'michael_b',
    'marion',
    'liujing',
    'jim',
  ],
  team_2: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bin',
    'bec',
    'bjorn',
    'chris',
    'du',
    'dunny',
    'duyen',
    'jatin',
    'jay',
  ],
  team_a: [
    'yixing',
    'yujin',
    'yingjian',
    'shuming',
    'ray',
    'ricky',
    'stacey',
    'sime',
    'michael_b',
    'marion',
    'liujing',
    'jim',
  ],
  'dropping_bombs': ['azra', 'shuming'],
  'silvinstones': ['dunny', 'chris'],
  'cowboy_needs_a_beer': ['alex', 'marion'],
  'go_duck': ['duyen', 'yixing'],
  'a_team': ['albert', 'andy'],
  'bake_my_day': ['michael_b', 'yujin'],
};
