import { PlayerList } from './types';

const tournamentTag = 'tournament';
const retired = 'retired';

export const ALL_PLAYERS: PlayerList = [
  { name: 'Albert', id: 'albert', avatarImageUrl: '/players/albert.png', tags: [tournamentTag] },
  { name: 'Alex', id: 'alex', avatarImageUrl: '/players/alex.png', tags: [tournamentTag] },
  { name: 'Andy', id: 'andy', avatarImageUrl: '/players/andy.png', tags: [tournamentTag] },
  { name: 'Azra', id: 'azra', avatarImageUrl: '/players/azra.png', tags: [tournamentTag] },
  { name: 'Bec', id: 'bec', avatarImageUrl: '/players/bec.png', tags: [tournamentTag] },
  { name: 'Bin', id: 'bin', avatarImageUrl: '/players/bin.png', tags: [tournamentTag] },
  { name: 'Bjorn', id: 'bjorn', avatarImageUrl: '/players/bjorn.png', tags: [retired] },
  { name: 'Chris', id: 'chris', avatarImageUrl: '/players/chris.png', tags: [tournamentTag] },
  { name: 'Du', id: 'du', avatarImageUrl: '/players/du.png', tags: [tournamentTag] },
  { name: 'Dunny', id: 'dunny', avatarImageUrl: '/players/dunny.png', tags: [tournamentTag] },
  { name: 'Duyen', id: 'duyen', avatarImageUrl: '/players/duyen.png', tags: [tournamentTag] },
  { name: 'Jatin', id: 'jatin', avatarImageUrl: '/players/jatin.png', tags: [retired] },
  { name: 'Jay', id: 'jay', avatarImageUrl: '/players/jay.png', tags: [tournamentTag] },
  { name: 'Jim', id: 'jim', avatarImageUrl: '/players/jim.png', tags: [tournamentTag] },
  { name: 'Liujing', id: 'liujing', avatarImageUrl: '/players/liujing.png', tags: [tournamentTag] },
  { name: 'Marion', id: 'marion', avatarImageUrl: '/players/marion.png', tags: [tournamentTag] },
  { name: 'Michael B', id: 'michael_b', avatarImageUrl: '/players/michael_b.png', tags: [tournamentTag] },
  { name: 'Stacey', id: 'stacey', avatarImageUrl: '/players/stacey.png', tags: [tournamentTag] },
  { name: 'Ray', id: 'ray', avatarImageUrl: '/players/ray.png', tags: [retired] },
  { name: 'Ricky', id: 'ricky', avatarImageUrl: '/players/ricky.png', tags: [tournamentTag] },
  { name: 'Shuming', id: 'shuming', avatarImageUrl: '/players/shuming.png', tags: [tournamentTag] },
  { name: 'Sime', id: 'sime', avatarImageUrl: '/players/sime.png', tags: [tournamentTag] },
  { name: 'Yingjian', id: 'yingjian', avatarImageUrl: '/players/yingjian.png', tags: [tournamentTag] },
  { name: 'Yixing', id: 'yixing', avatarImageUrl: '/players/yixing.png', tags: [tournamentTag] },
  { name: 'Yujin', id: 'yujin', avatarImageUrl: '/players/yujin.png', tags: [tournamentTag] },
];

export const ALL_TEAMS = [
  { id: 'xian', name: 'Xian' },
  { id: 'melb', name: 'Melbourne' },
  { id: 'us', name: 'Us' },
  { id: 'them', name: 'Them' },
  { id: 'team_a', name: 'Team A' },
  { id: 'team_2', name: 'Team 2' },
  { id: 'dropping_bombs', name: 'Dropping Bombs' },
  { id: 'silvinstones', name: 'Silvinstones' },
  { id: 'cowboy_needs_a_beer', name: 'Cowboy Needs a Beer' },
  { id: 'go_duck', name: 'Go Duck' },
  { id: 'a_team', name: 'The A Team' },
  { id: 'bake_my_day', name: 'Bake My Day' },
  { id: 'fatboy_slim', name: 'Fatboy Slim' },
  { id: 'developers', name: 'Developers' },
  { id: 'bas', name: 'Business Analysts' },
];

export const PLAYER_IDS_BY_TEAM: { [teamId: string]: string[] } = {
  xian: ['bin', 'shuming', 'yingjian', 'yixing'],
  melb: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bjorn',
    'chris',
    'du',
    'duyen',
    'jatin',
    'jay',
    'jim',
    'liujing',
    'marion',
    'michael_b',
    'stacey',
    'ray',
    'ricky',
    'yujin',
  ],
  us: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bin',
    'bjorn',
    'chris',
    'du',
    'duyen',
    'jatin',
    'jay',
  ],
  them: [
    'yixing',
    'yujin',
    'yingjian',
    'shuming',
    'ray',
    'stacey',
    'michael_b',
    'marion',
    'liujing',
    'jim',
  ],
  team_2: [
    'albert',
    'alex',
    'andy',
    'azra',
    'bin',
    'bec',
    'bjorn',
    'chris',
    'du',
    'dunny',
    'duyen',
    'jatin',
    'jay',
  ],
  team_a: [
    'yixing',
    'yujin',
    'yingjian',
    'shuming',
    'ray',
    'ricky',
    'stacey',
    'sime',
    'michael_b',
    'marion',
    'liujing',
    'jim',
  ],
  'dropping_bombs': ['azra', 'shuming'],
  'silvinstones': ['dunny', 'chris'],
  'cowboy_needs_a_beer': ['alex', 'chris'],
  'go_duck': ['duyen', 'yixing'],
  'a_team': ['albert', 'andy'],
  'bake_my_day': ['michael_b', 'yujin'],
  'fatboy_slim': ['jay', 'bec'],
  'developers': ['michael_b', 'du'],
  'bas': ['alex', 'marion'],
};
